### ISSUE TITLE
这个应用程序被换过图标，同时这个图标在现在这台电脑上打开会显示无法预览

### ISSUE THREAD

**Issue by AkatsukiNoKag** [FlandreDevs/Sakuya#1]
![image](https://user-images.githubusercontent.com/85553453/222738195-e46f5ffc-2b2a-489f-9b87-e757082c4f2c.png)

**Comment by bsdayo** [comment]
（挠头
~我这里是正常的，可以看下你那边有没有这个文件~
已修复
